os: linux
dist: bionic
language: python

python:
  - "3.8"

cache:
  - pip: true
  - apt: true

addons:
  apt:
    update: true
    packages:
      - unzip
      - exiftool
      - libstdc++6
      - libtiff5-dev
      - build-essential
      - make

env:
  global:
    - KAKADU_HOME_PATH=/opt/kakadu
    - AVI_FILES_DIR="${HOME}/avi-files"
    - AVI_DEBUG=true
    - MAGICK_MEMORY_LIMIT=512

before_install:
  - wget https://www.imagemagick.org/download/ImageMagick.tar.gz
  - tar xzvf ImageMagick.tar.gz
  - cd ImageMagick-7.*
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig /usr/local/lib
  - cd ..
  - wget http://kakadusoftware.com/wp-content/uploads/KDU805_Demo_Apps_for_Linux-x86-64_200602.zip
  - unzip KDU805_Demo_Apps_for_Linux-x86-64_200602.zip
  - mv KDU805_Demo_Apps_for_Linux-x86-64_200602 $KAKADU_HOME_PATH
  - PATH=$PATH:$KAKADU_HOME_PATH
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KAKADU_HOME_PATH
  - export PATH
  - export LD_LIBRARY_PATH

install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev
script:
  - pylint avi_py/ && pytest --cov=avi_py/

after_success:
  - coveralls
