os: linux
dist: focal
language: python

python:
  - "3.8"

cache:
  - pip: true
  - apt: true

virtualenv:
  system_site_packages: true

addons:
  apt:
    update: true
    packages:
      - unzip
      - exiftool
      - libstdc++6
      - libtiff5-dev
      - build-essential
      - make

env:
  global:
    - PYTHON=3.8.17
    - KAKADU_HOME=/opt/kakadu
    - AVI_DEBUG=true
    - MAGICK_MEMORY_LIMIT=512
    - OMP_THREAD_LIMIT=1
before_install:
  - sudo apt-get install -y tesseract-ocr ffmpeg
  - wget https://imagemagick.org/archive/ImageMagick.tar.gz
  - tar xzvf ImageMagick.tar.gz
  - cd ImageMagick-7.*
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig /usr/local/lib
  - cd ..
  - wget http://kakadusoftware.com/wp-content/uploads/KDU805_Demo_Apps_for_Linux-x86-64_200602.zip
  - unzip KDU805_Demo_Apps_for_Linux-x86-64_200602.zip
  - mv KDU805_Demo_Apps_for_Linux-x86-64_200602 $KAKADU_HOME
  - PATH=$PATH:$KAKADU_HOME
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KAKADU_HOME
  - export PATH
  - export LD_LIBRARY_PATH

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
script:
  - pylint avi_py/ && pytest --cov=avi_py/
after_success:
  - coveralls
