os: linux
dist: bionic
language: python

python:
  - "3.8"

cache:
  - pip: true
  - apt: true

addons:
  apt:
    packages:
      - unzip
      - exiftool
      - libstdc++6
      - imagemagick
env:
  global:
    - KAKADU_HOME_PATH=/opt/kakadu
    - AVI_FILES_DIR="${HOME}/avi-files"
    - AVI_DEBUG=true

install:
  - wget http://kakadusoftware.com/wp-content/uploads/KDU805_Demo_Apps_for_Linux-x86-64_200602.zip
  - unzip KDU805_Demo_Apps_for_Linux-x86-64_200602.zip
  - mv KDU805_Demo_Apps_for_Linux-x86-64_200602 $KAKADU_HOME_PATH
  - PATH=$PATH:$KAKADU_HOME_PATH
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KAKADU_HOME_PATH
  - export PATH
  - export LD_LIBRARY_PATH
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev
script:
  - pipenv run pylint avi_py/ && pipenv run pytest --cov=avi_py/

after_success:
  - pipenv run coveralls
