name: Build branches

on: [push, pull_request]

env:
  PYTHON: "3.10.20"
  KAKADU_HOME: /opt/kakadu
  AVI_DEBUG: "true"
  MAGICK_MEMORY_LIMIT: "512"
  OMP_THREAD_LIMIT: "1"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # cache: pip

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            unzip \
            exiftool \
            libstdc++6 \
            libtiff5-dev \
            build-essential \
            make \
            tesseract-ocr \
            ffmpeg

      - name: Setup ImageMagick 7
        uses: mfinelli/setup-imagemagick@v8.0.0

      - name: Install Kakadu
        run: |
          wget \
            --user-agent="Mozilla/5.0" \
            -O KDU841_Demo_Apps_for_Linux-x86-64_231117.zip \
            "https://kakadusoftware.com/wp-content/uploads/KDU841_Demo_Apps_for_Linux-x86-64_231117.zip"
          unzip KDU841_Demo_Apps_for_Linux-x86-64_231117.zip
          sudo mv KDU841_Demo_Apps_for_Linux-x86-64_231117 $KAKADU_HOME
          echo "$KAKADU_HOME" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${{ env.KAKADU_HOME }}:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Lint with pylint
        run: pipenv run pylint avi_py/

      - name: Run tests with coverage
        run: pipenv run pytest --cov=avi_py/